### ISSUE TITLE
bot instances not running correctly on Windows OS

### ISSUE THREAD

**Issue by mrazishere** [mrazishere/Twitch-Chatbot-Deployment#1]
The bot deployment runs just fine however the bot app(new-template.js) is not running correctly on windows.
Suspected how Windows treats slashes in paths vs Linux(forward vs back slashes)

```
0|Bot-Deployment-Manager  | 2023-02-19: [11:59] info: [#mraiishere] <mrazishere>: test
2|mraiishere              | 2023-02-19: TypeError: commands.translate is not a function
2|mraiishere              | 2023-02-19:     at client.<anonymous> (C:\Users\MrAZ\Twitch-Chatbot-Deployment\channels\mraiishere.js:188:26)
2|mraiishere              | 2023-02-19:     at EventEmitter.emit (C:\Users\MrAZ\Twitch-Chatbot-Deployment\node_modules\tmi.js\lib\events.js:88:13)
2|mraiishere              | 2023-02-19:     at client.emits (C:\Users\MrAZ\Twitch-Chatbot-Deployment\node_modules\tmi.js\lib\client.js:90:13)
2|mraiishere              | 2023-02-19:     at client.handleMessage (C:\Users\MrAZ\Twitch-Chatbot-Deployment\node_modules\tmi.js\lib\client.js:1117:13)
2|mraiishere              | 2023-02-19:     at C:\Users\MrAZ\Twitch-Chatbot-Deployment\node_modules\tmi.js\lib\client.js:1228:9
2|mraiishere              | 2023-02-19:     at Array.forEach (<anonymous>)
2|mraiishere              | 2023-02-19:     at client._onMessage (C:\Users\MrAZ\Twitch-Chatbot-Deployment\node_modules\tmi.js\lib\client.js:1225:8)
2|mraiishere              | 2023-02-19:     at callListener (C:\Users\MrAZ\Twitch-Chatbot-Deployment\node_modules\tmi.js\node_modules\ws\lib\event-target.js:290:14)
2|mraiishere              | 2023-02-19:     at WebSocket.onMessage (C:\Users\MrAZ\Twitch-Chatbot-Deployment\node_modules\tmi.js\node_modules\ws\lib\event-target.js:209:9)
2|mraiishere              | 2023-02-19:     at WebSocket.emit (node:events:512:28)
```

https://github.com/mrazishere/Twitch-Chatbot-Deployment/blob/b7c4da0d0964073aac53e9394bcfaf6c5c1c8b21/channels/new-template.js#L111

**Comment by mrazishere** [comment]
might relate to https://github.com/isaacs/node-glob#windows

No plans for fix for now as linux vm is easily available for Windows now
